### ISSUE TITLE
下拉刷新，不清除当前列表，向下滑动时候会报错

### ISSUE THREAD

**Issue by wpj19910910** [shucc/RecyclerViewDemo#3]
if (pageNum == 1) {
            data.clear();
            //不清除当前views,滑动时候会报错
            recyclerView.removeAllViews();
        }

**Comment by shucc** [comment]
@wpj19910910 这是由于data数据清空时adapter没及时同步数据导致的，所以异步请求数据要清空数据重新添加数据时，需要在清空数据后马上加上adapter的刷新处理，我修改了下demo，把data.clear()放到了异步数据请求成功里面，你可以看下

**Comment by wpj19910910** [comment]
嗯 懂了 你是想要数据成功返回才重新刷新列表

**Comment by shucc** [comment]
是的，这是RecyclerView的机制决定的
